Heatsink [TCA]:
  Contour Points: 400
  Nozzle Type: Bell
  Throat Radius (in): 1.2
  Chamber Length (in): 7.9
  Contraction Ratio: 2
  Convergence Half-Angle (°): 37.5
  Convergence Radius Factor: 1
  Lead-in Radius Factor: 1
  Lead-out Radius Factor: 0.5
  Expansion Ratio: 6
  Ambient Pressure (psia): 14.7
  Combustor Area: Finite
  Divergence Half-Angle (°): 15
  Divergence Entrance Angle (°): 22
  Divergence Exit Angle (°): 10
  Percent Bell (%): 80
Coax [Component]: {}
